class Recipe {
  String label;
  String imageUrl;

  int servings;
  List<Ingredient> ingredients;

  Recipe(this.label, this.imageUrl, this.servings, this.ingredients);

  static List<Recipe> samples = [
    Recipe(
      'Soto Lamongan',
      'assets/soto_lamongan.jpg',
      1,
      [
        Ingredient(0.5, ' kg', ' Ayam fillet/Dada Mentok'),
        Ingredient(10, ' siung', ' Bawang merah'),
        Ingredient(8, ' siung', ' Bawang putih'),
        Ingredient(0.25, ' sdt', ' Pala bubuk'),
        Ingredient(1, ' sdm', ' Ketumbar bubuk'),
        Ingredient(5, ' butir', ' Kemiri sangrai'),
        Ingredient(0.5, ' sdm', ' Kunyit bubuk'),
        Ingredient(1, ' ruas', ' Jahe'),
        Ingredient(2, ' batang', ' Lengkuas'),
        Ingredient(3, ' batang', ' Sereh'),
        Ingredient(5, ' lembar', ' Daun jeruk'),
        Ingredient(2, ' batang', ' Seledri'),
        Ingredient(3, ' batang', ' Daun pre'),
      ],
    ),
    Recipe(
      'Sate Madura',
      'assets/sate_madura.jpeg',
      5,
      [
        Ingredient(500, ' gram', ' Dada ayam'),
        Ingredient(1, ' siung', ' Bawang putih giling'),
        Ingredient(2, ' sdt', ' Lada bubuk'),
        Ingredient(1, ' sdt', ' Garam'),
        Ingredient(200, ' gram', ' Kacang tanah'),
        Ingredient(5, ' siung', ' Bawang merah'),
        Ingredient(5, ' siung', ' Bawang putih'),
        Ingredient(0.5, ' sdm', ' Cabai merah giling'),
        Ingredient(1, ' buah', ' kemiri'),
        Ingredient(2, ' sdt', ' Gula merah'),
        Ingredient(2, ' sdm', ' Royco'),
        Ingredient(2, ' gelas', ' Air'),
        Ingredient(0.5, ' cangkir', ' Kecap Manis'),
      ],
    ),
    Recipe(
      'Bakso Malang',
      'assets/bakso_malang.jpeg',
      3,
      [
        Ingredient(9, ' buah', ' Siomay basah'),
        Ingredient(9, ' buah', ' Siomay kering'),
        Ingredient(3, ' buah', ' Pangsit kering'),
        Ingredient(9, ' buah', ' Tahu sumedang'),
        Ingredient(600, ' ml', ' Air'),
        Ingredient(1, ' batang', ' Seledri'),
        Ingredient(1, ' batang', ' Daun bawang'),
        Ingredient(0.5, ' cangkir', ' Kecap Manis'),
        Ingredient(0.5, ' cangkir', ' Saus'),
        Ingredient(0.25, ' cangkir', ' Bawang goreng'),
        Ingredient(2, ' lembar', ' Daun jeruk'),
        Ingredient(2, ' siung', ' Bawang putih'),
        Ingredient(5, ' butir', ' Merica'),
        Ingredient(1, ' sdt', ' Garam'),
        Ingredient(1, ' sdt', ' Kaldu jamur'),
      ],
    ),
    Recipe(
      'Pecel Madiun',
      'assets/pecel_madiun.jpg',
      1,
      [
        Ingredient(250, ' gram', ' Kacang tanah'),
        Ingredient(5, ' siung', ' Bawang putih'),
        Ingredient(3, ' buah', ' Cabai merah besar'),
        Ingredient(5, ' lembar', ' Daun jeruk'),
        Ingredient(0.5, ' sdm', ' Asam jawa'),
        Ingredient(1, ' ruas', ' Kencur'),
        Ingredient(50, ' gram', ' Gula merah sisir'),
        Ingredient(1, ' sdm', ' Garam'),
        Ingredient(1, ' sdm', ' Kaldu bubuk'),
        Ingredient(100, ' gram', ' Taoge'),
        Ingredient(150, ' gram', ' Kangkung'),
        Ingredient(100, ' gram', ' Kacang panjang'),
        Ingredient(2, ' potong', ' Tahu goreng'),
        Ingredient(2, ' potong', ' Tempe goreng'),
      ],
    ),
    Recipe(
      'Rujak Cingur',
      'assets/rujak_cingur.jpg',
      1,
      [
        Ingredient(100, ' gram', ' Cingur sapi'),
        Ingredient(2, ' buah', ' Tahu goreng'),
        Ingredient(2, ' potong', ' Tempe goreng'),
        Ingredient(1, ' buah', ' Mentimun'),
        Ingredient(3, ' helai', ' Krai kukus'),
        Ingredient(100, ' gram', ' Kangkung rebus'),
        Ingredient(100, ' gram', ' Kecambah rebus'),
        Ingredient(150, ' gram', ' Bengkuang'),
        Ingredient(2, ' potong', ' Lontong'),
        Ingredient(1, ' buah', ' Cabai'),
        Ingredient(1, ' buah', ' Pisang klutuk iris tipis'),
        Ingredient(1, ' sdt', ' Asam jawa'),
        Ingredient(0.5, ' sdm', ' Gula'),
        Ingredient(0.25, ' sdt', ' Garam'),
        Ingredient(3, ' sdm',
            ' Kacang goreng yang dicampur dengan bawang putih goreng'),
        Ingredient(4, ' sdm', ' Petis udang'),
        Ingredient(50, ' ml', ' Air matang'),
      ],
    ),
    Recipe(
      'Rawon',
      'assets/rawon.jpg',
      5,
      [
        Ingredient(1, ' kg', ' Daging sapi'),
        Ingredient(1, ' sdm', ' Ketumbar bubuk'),
        Ingredient(1, ' sdm', ' Jinten bubuk'),
        Ingredient(4, ' gram', ' Jahe'),
        Ingredient(2, ' lembar', ' Daun jeruk'),
        Ingredient(
            3, ' batang', ' Serai (yang sudah digeprek atau dimemarkan)'),
        Ingredient(6, ' buah', ' Keluak (rendam dengan air panas)'),
        Ingredient(2, ' sdm', ' Garam'),
        Ingredient(1, ' sdt', ' Kaldu sapi bubuk tanpa MSG'),
        Ingredient(10, ' siung', ' Bawang merah'),
        Ingredient(8, ' siung', ' Bawang putih'),
      ],
    ),
    Recipe(
      'Lontong Balap',
      'assets/lontong_balap.jpeg',
      1,
      [
        Ingredient(1, ' ons', ' Kecambah atau taoge'),
        Ingredient(2, ' batang', ' Daun bawang'),
        Ingredient(2, ' batang', ' Daun seledri'),
        Ingredient(1, ' sdm', ' Kecap manis'),
        Ingredient(250, ' ml', ' Air'),
        Ingredient(3, ' siung', ' Bawang merah'),
        Ingredient(2, ' siung', ' Bawang putih'),
        Ingredient(0.5, ' sdt', ' Garam'),
        Ingredient(0.25, ' sdt', ' Merica bubuk'),
        Ingredient(0.25, ' buah', ' Lontong'),
        Ingredient(1, ' sendok', ' Petis yang sudah diracik'),
        Ingredient(2, ' potong', ' Tahu goreng'),
        Ingredient(0.25, ' cangkir', ' Bawang goreng'),
      ],
    ),
    Recipe(
      'Tahu Tek',
      'assets/tahu_tek.jpg',
      1,
      [
        Ingredient(1, ' kotak', ' Tahu ukuran kecil (goreng matang)'),
        Ingredient(1, ' butir', ' Telur (dibuat dadar polos)'),
        Ingredient(0.5, ' buah', ' Kentang (goreng)'),
        Ingredient(3, ' potong', ' Lontong'),
        Ingredient(0.25, ' buah', ' Mentimun (iris)'),
        Ingredient(100, ' gram', ' Taoge'),
        Ingredient(5, ' buah', ' Kerupuk udang kecil'),
        Ingredient(1, ' genggam', ' Kacang tanah goreng'),
        Ingredient(1, ' sdm', ' Petis udang'),
        Ingredient(1, ' siung', ' Bawang putih'),
        Ingredient(3, ' buah', ' Cabai rawit merah'),
        Ingredient(0.25, ' sdt', ' Garam'),
        Ingredient(1, ' sdt', ' Kecap Manis'),
      ],
    ),
    Recipe(
      'Nasi Krawu',
      'assets/nasi_krawu.jpeg',
      5,
      [
        Ingredient(0.5, ' kg', ' Daging sapi'),
        Ingredient(3, ' buah', ' Gula merah'),
        Ingredient(2, ' lembar', ' Daun salam'),
        Ingredient(0.5, ' sdt', ' Asam jawa'),
        Ingredient(8, ' siung', ' Bawang merah'),
        Ingredient(5, ' siung', ' Bawang putih'),
        Ingredient(1, ' sdm', ' Ketumbar'),
        Ingredient(2, ' buah', ' Cabai merah besar'),
        Ingredient(5, ' buah', ' Cabai rawit'),
        Ingredient(200, ' ml', ' Air kaldu rebusan daging'),
        Ingredient(2, ' sdm', ' Minyak goreng'),
      ],
    ),
    Recipe(
      'Ayam Lodho',
      'assets/ayam_lodho.jpg',
      5,
      [
        Ingredient(
            1, ' ekor', ' Ayam kampung atau ayam biasa utuh (potong-potong)'),
        Ingredient(10, ' siung', ' Bawang merah'),
        Ingredient(7, ' siung', ' Bawang putih'),
        Ingredient(1, ' ruas', ' Kunyit'),
        Ingredient(1, ' ruas', ' Jahe'),
        Ingredient(1, ' ruas', ' Kencur'),
        Ingredient(10, ' buah', ' Cabai rawit'),
        Ingredient(4, ' lembar', ' Daun jeruk'),
        Ingredient(2, ' lembar', ' Daun salam'),
        Ingredient(2, ' batang', ' Sereh'),
        Ingredient(1, ' ruas', ' Laos'),
        Ingredient(1, ' sdm', ' Gula merah'),
        Ingredient(1, ' sachet', ' Santan kelapa instan'),
        Ingredient(0.25, ' sdt', ' Garam'),
        Ingredient(0.5, ' sdt', ' Gula'),
        Ingredient(1, ' sdt', ' Kaldu jamur'),
      ],
    ),
  ];
}

class Ingredient {
  double quantity;
  String measure;
  String name;

  Ingredient(this.quantity, this.measure, this.name);
}
